In [11]:
#Quetsion 1

# practice 2.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
33      1   0   1   1   1   0   0   1   1   1  ...    1    0    0    1    1   
64      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
19      1   1   0   0   0   1   0   0   0   0  ...    1    0    0    0    0   
53      0   0   0   1   0   0   0   0   0   0  ...    1    0    0    0    0   
9       1   0   1   0   0   0   0   1   1   0  ...    0    0    0    0    0   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
0       1   0   0   0   1   0   0   0   1   1  ...    1    1    0    0    0   
49      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
25      1   0   0   0   0   0   0   1   0   0  ...    0    0    0    1    0   
57      0   1   1   1   0   1   0   1   1   1  ...    0    1    0    1    0   
59      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

    F18  F19  F20  F21  F22  
33    1    0    0    1    1  
64    0    0    0    0    0  
19    0    0    1    0    0  
53    0    0    0    0    0  
9     0    0    0    0    0  
..  ...  ...  ...  ...  ...  
0     0    0    0    0    0  
49    0    0    1    0    0  
25    0    0    0    0    0  
57    0    1    0    1    0  
59    0    0    0    0    0  

[80 rows x 23 columns]

In [12]:
# practice 2.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [13]:
# practice 2.3: import Sequential class and Dense class from keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
# practice 2.4: build a three-layer neural network with binary function as output
model = Sequential()
model.add()

TypeError: ignored

In [15]:
from keras.regularizers import l2

model_reg = Sequential() # create Sequential model
model_reg.add(Dense(100, activation = 'relu', kernel_regularizer=l2(0.1), bias_regularizer=l2(0.1)))
model_reg.add(Dense (100, activation = 'relu', kernel_regularizer=l2(0.1), bias_regularizer=l2(0.1)))
model_reg.add(Dense(1, activation = 'sigmoid', kernel_regularizer=l2(0.1), bias_regularizer=l2(0.1)))
model_reg.compile(loss = "binary _crossentropy", optimizer = "SGD", metrics = ['accuracy'])


In [16]:
#Question 2

## Practice 3.1: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [17]:
## Practice 3.2: Define the first hidden layer in model architecture
from keras.models import Sequential
from keras.layers import Dense
model = Sequential() # initialize Sequential model

# add connection layers into sequential model
model.add(Dense(100, input_shape=(22,),activation='relu')) # input layer -> hidden layer 1

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 100)               2300      
                                                                 
Total params: 2,300
Trainable params: 2,300
Non-trainable params: 0
_________________________________________________________________


In [18]:
#Question 3

## Practice 4: Add more hidden layers and output layers into network
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 100)               2300      
                                                                 
 dense_5 (Dense)             (None, 100)               10100     
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [19]:
#Question 4

## Practice 5.1: Compile the model for backpropagation, and start training model on data
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(100, input_shape=(22,), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(100, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(1, activation='sigmoid')) # hidden layer 2 -> output layer

# Compile model, use binary crossentropy, and stochastic gradient descent for optimization
model.compile(loss='binary_crossentropy', optimizer='SGD', metrics=['accuracy'])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 100)               2300      
                                                                 
 dense_8 (Dense)             (None, 100)               10100     
                                                                 
 dense_9 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [20]:
## Practice 5.2: start training the model on the features and labels, set the training epochs to 10 
model.fit(train_features, train_label, epochs = 10)

Epoch 1/10
3/3 [==============================] - 1s 11ms/step - loss: 0.6726 - accuracy: 0.6000
Epoch 2/10
3/3 [==============================] - 0s 7ms/step - loss: 0.6702 - accuracy: 0.6375
Epoch 3/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6677 - accuracy: 0.6375
Epoch 4/10
3/3 [==============================] - 0s 12ms/step - loss: 0.6652 - accuracy: 0.6125
Epoch 5/10
3/3 [==============================] - 0s 9ms/step - loss: 0.6634 - accuracy: 0.6125
Epoch 6/10
3/3 [==============================] - 0s 9ms/step - loss: 0.6608 - accuracy: 0.6125
Epoch 7/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6588 - accuracy: 0.6125
Epoch 8/10
3/3 [==============================] - 0s 9ms/step - loss: 0.6570 - accuracy: 0.6375
Epoch 9/10
3/3 [==============================] - 0s 6ms/step - loss: 0.6555 - accuracy: 0.6375
Epoch 10/10
3/3 [==============================] - 0s 9ms/step - loss: 0.6530 - accuracy: 0.6375


In [21]:
model.fit(train_features, train_label, epochs = 100)

Epoch 1/100
3/3 [==============================] - 0s 10ms/step - loss: 0.6514 - accuracy: 0.6375
Epoch 2/100
3/3 [==============================] - 0s 10ms/step - loss: 0.6499 - accuracy: 0.6375
Epoch 3/100
3/3 [==============================] - 0s 11ms/step - loss: 0.6480 - accuracy: 0.6375
Epoch 4/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6468 - accuracy: 0.6375
Epoch 5/100
3/3 [==============================] - 0s 9ms/step - loss: 0.6452 - accuracy: 0.6375
Epoch 6/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6437 - accuracy: 0.6375
Epoch 7/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6424 - accuracy: 0.6375
Epoch 8/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6410 - accuracy: 0.6375
Epoch 9/100
3/3 [==============================] - 0s 10ms/step - loss: 0.6396 - accuracy: 0.6375
Epoch 10/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6379 - accuracy: 0.6375
Epoch 11/100
3/3 [=======

In [22]:
model.fit(train_features, train_label, epochs = 1000)

Epoch 1/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.5475 - accuracy: 0.7625
Epoch 2/1000
3/3 [==============================] - 0s 7ms/step - loss: 0.5469 - accuracy: 0.7750
Epoch 3/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.5461 - accuracy: 0.7750
Epoch 4/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.5451 - accuracy: 0.7750
Epoch 5/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.5445 - accuracy: 0.7750
Epoch 6/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.5436 - accuracy: 0.7750
Epoch 7/1000
3/3 [==============================] - 0s 6ms/step - loss: 0.5431 - accuracy: 0.7750
Epoch 8/1000
3/3 [==============================] - 0s 7ms/step - loss: 0.5420 - accuracy: 0.7750
Epoch 9/1000
3/3 [==============================] - 0s 7ms/step - loss: 0.5413 - accuracy: 0.7750
Epoch 10/1000
3/3 [==============================] - 0s 5ms/step - loss: 0.5404 - accuracy: 0.7750
Epoch 11/1000
3/3 [

In [23]:
## practice 6.1: save the model to local disk, or load the model for predictions
from tensorflow.keras.models import load_model
model.save("SPECT.h5")


In [24]:
model_loaded = load_model("SPECT.h5")

In [25]:
## practice 6.2: evaluate the model performance using evaluate() method
model_loaded.evaluate(train_features, train_label)

3/3 [==============================] - 0s 6ms/step - loss: 0.2074 - accuracy: 0.9375


[0.20744934678077698, 0.9375]

In [26]:
## practice 6.3: make a prediction on training set and test set
train_predictions = model_loaded.predict(train_features)
test_predictions = model_loaded.predict(test_features)
print("train_predictions: ",train_predictions) # the prediction is the probability of the class

6/6 [==============================] - 0s 3ms/step
train_predictions:  [[0.9999054 ]
 [0.0986757 ]
 [0.9229839 ]
 [0.06953715]
 [0.9576059 ]
 [0.99809444]
 [0.0986757 ]
 [0.32227603]
 [0.0986757 ]
 [0.09061053]
 [0.0986757 ]
 [0.7964243 ]
 [0.14665417]
 [0.9191425 ]
 [0.9097684 ]
 [0.25544032]
 [0.948404  ]
 [0.2654449 ]
 [0.926591  ]
 [0.0986757 ]
 [0.25544032]
 [0.34500194]
 [0.9756251 ]
 [0.09995323]
 [0.99476975]
 [0.03185053]
 [0.19034782]
 [0.91387916]
 [0.0986757 ]
 [0.89662975]
 [0.21255949]
 [0.81718236]
 [0.34500194]
 [0.07840173]
 [0.25544032]
 [0.0986757 ]
 [0.0986757 ]
 [0.0986757 ]
 [0.9496943 ]
 [0.9845212 ]
 [0.13979124]
 [0.98404616]
 [0.9999884 ]
 [0.9995166 ]
 [0.9689586 ]
 [0.07832841]
 [0.80654454]
 [0.11239715]
 [0.9673589 ]
 [0.98755765]
 [0.25544032]
 [0.9995813 ]
 [0.18948263]
 [0.14446208]
 [0.96692824]
 [0.13921812]
 [0.9785491 ]
 [0.99510753]
 [0.90233946]
 [0.98955417]
 [0.0986757 ]
 [0.0986757 ]
 [0.24769081]
 [0.12472285]
 [0.9997949 ]
 [0.994729  ]
 [0.0

In [27]:
## practice 6.4: convert probability to labels
import numpy as np
train_prediction_labels = (train_predictions > 0.5).astype(int)
test_prediction_labels = (test_predictions > 0.5).astype(int)

In [28]:
## practice 6.5: convert probability to labels
from sklearn.metrics import accuracy_score
print("Training accuracy: ", accuracy_score(train_label, train_prediction_labels))
print("Test accuracy: ", accuracy_score(test_label, test_prediction_labels))

Training accuracy:  0.9375
Test accuracy:  0.7700534759358288


In [29]:
from sklearn.metrics import f1_score, precision_score, recall_score
print("Training f1-score: ", f1_score(train_label, train_prediction_labels))
print("Test f1-score: ", f1_score(test_label, test_prediction_labels))

print("Training precision: ", precision_score(train_label, train_prediction_labels))
print("Test precision: ", precision_score(test_label, test_prediction_labels))

print("Training recall: ", recall_score(train_label, train_prediction_labels))
print("Test recall: ", recall_score(test_label, test_prediction_labels))

Training f1-score:  0.9333333333333333
Test f1-score:  0.8599348534201955
Training precision:  1.0
Test precision:  0.9777777777777777
Training recall:  0.875
Test recall:  0.7674418604651163


In [30]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 100)               2300      
                                                                 
 dense_8 (Dense)             (None, 100)               10100     
                                                                 
 dense_9 (Dense)             (None, 1)                 101       
                                                                 
Total params: 12,501
Trainable params: 12,501
Non-trainable params: 0
_________________________________________________________________


In [31]:
# practice 7.1: Load training data
import pandas as pd
from sklearn.utils import shuffle
train_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.train', header=None)
train_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
train_data = shuffle(train_data) # shuffle data
train_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
25      1   0   0   0   0   0   0   1   0   0  ...    0    0    0    1    0   
58      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
64      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
10      1   1   1   0   0   1   0   1   0   0  ...    1    0    0    1    1   
16      1   0   0   1   1   0   0   0   1   1  ...    1    1    0    1    0   
..    ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
21      1   1   0   0   0   1   1   0   1   0  ...    0    0    0    0    0   
6       1   1   0   1   1   0   0   0   1   0  ...    1    0    0    0    0   
53      0   0   0   1   0   0   0   0   0   0  ...    1    0    0    0    0   
32      1   1   1   0   0   1   1   1   0   0  ...    0    0    0    0    1   
78      0   0   0   1   1   0   0   1   0   0  ...    1    1    0    0    0   

    F18  F19  F20  F21  F22  
25    0    0    0    0    0  
58    0    0    0    0    0  
64    0    0    0    0    0  
10    1    1    1    0    1  
16    0    0    0    1    0  
..  ...  ...  ...  ...  ...  
21    0    1    1    0    0  
6     0    0    0    1    1  
53    0    0    0    0    0  
32    0    1    0    0    1  
78    0    0    0    1    1  

[80 rows x 23 columns]

In [32]:
# practice 7.2: Load testing data
import pandas as pd
test_data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spect/SPECT.test', header=None)
test_data.columns = ['Label']+[ 'F'+str(i) for i in range(1,23)]
test_data

Label  F1  F2  F3  F4  F5  F6  F7  F8  F9  ...  F13  F14  F15  F16  F17  \
0        1   1   0   0   1   1   0   0   0   1  ...    0    1    1    1    0   
1        1   1   0   0   1   1   0   0   0   0  ...    1    0    0    0    0   
2        1   0   0   0   1   0   1   0   0   1  ...    0    1    1    0    0   
3        1   0   1   1   1   0   0   1   0   1  ...    1    1    0    1    0   
4        1   0   0   1   0   0   0   0   1   0  ...    1    1    0    1    0   
..     ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
182      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   
183      0   1   1   0   0   0   1   0   0   0  ...    0    0    0    1    0   
184      0   1   0   1   0   1   0   0   1   0  ...    1    0    1    1    0   
185      0   1   0   1   0   1   0   0   1   1  ...    0    1    0    1    0   
186      0   0   0   0   0   0   0   0   0   0  ...    0    0    0    0    0   

     F18  F19  F20  F21  F22  
0      0    1    1    0    0  
1      0    0    0    0    0  
2      0    0    0    0    1  
3      0    0    0    1    0  
4      0    0    0    0    1  
..   ...  ...  ...  ...  ...  
182    0    0    0    0    0  
183    0    0    0    0    0  
184    0    0    0    0    0  
185    0    0    0    0    0  
186    0    0    0    0    0  

[187 rows x 23 columns]

In [33]:
## Practice 7.3: extract features and labels from the training/test data
train_label = train_data['Label']
train_features = train_data.drop('Label',axis= 1)
print("train_features.shape:",train_features.shape)

test_label = test_data['Label']
test_features = test_data.drop('Label',axis=1)
print("test_features.shape:",test_features.shape)

train_features.shape: (80, 22)
test_features.shape: (187, 22)


In [34]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, f1_score


model_sklearn = MLPClassifier(hidden_layer_sizes=(100, 100), activation='relu', solver='adam', alpha=0.0001, max_iter=1000, random_state=42)
model_sklearn.fit(train_features, train_label)


y_pred_sklearn = model_sklearn.predict(test_features)
accuracy_sklearn = accuracy_score(test_label, y_pred_sklearn)
f1_sklearn = f1_score(test_label, y_pred_sklearn)

print("Accuracy (sklearn): {:.4f}".format(accuracy_sklearn))
print("F1-score (sklearn): {:.4f}".format(f1_sklearn))



Accuracy (sklearn): 0.7112
F1-score (sklearn): 0.8188


In [35]:
#Question 7

# Practice 8.1: Monitor the model performance using validation set
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size=0.2, random_state=42)

## option 1: monitor the model training using validation data
model.fit(X_train, y_train, validation_data= (X_val, y_val), epochs = 20)

Epoch 1/20
2/2 [==============================] - 1s 1s/step - loss: 0.2238 - accuracy: 0.9375 - val_loss: 0.1440 - val_accuracy: 0.9375
Epoch 2/20
2/2 [==============================] - 0s 61ms/step - loss: 0.2234 - accuracy: 0.9375 - val_loss: 0.1441 - val_accuracy: 0.9375
Epoch 3/20
2/2 [==============================] - 0s 54ms/step - loss: 0.2233 - accuracy: 0.9375 - val_loss: 0.1442 - val_accuracy: 0.9375
Epoch 4/20
2/2 [==============================] - 0s 67ms/step - loss: 0.2232 - accuracy: 0.9375 - val_loss: 0.1444 - val_accuracy: 0.9375
Epoch 5/20
2/2 [==============================] - 0s 71ms/step - loss: 0.2230 - accuracy: 0.9375 - val_loss: 0.1444 - val_accuracy: 0.9375
Epoch 6/20
2/2 [==============================] - 0s 82ms/step - loss: 0.2228 - accuracy: 0.9375 - val_loss: 0.1445 - val_accuracy: 0.9375
Epoch 7/20
2/2 [==============================] - 0s 120ms/step - loss: 0.2228 - accuracy: 0.9375 - val_loss: 0.1446 - val_accuracy: 0.9375
Epoch 8/20
2/2 [============

In [36]:
## option 2: monitor the model training using validation data
model.fit(X_train, y_train, validation_split=0.2, epochs = 20)

Epoch 1/20
2/2 [==============================] - 0s 153ms/step - loss: 0.2293 - accuracy: 0.9412 - val_loss: 0.1894 - val_accuracy: 0.9231
Epoch 2/20
2/2 [==============================] - 0s 59ms/step - loss: 0.2287 - accuracy: 0.9412 - val_loss: 0.1913 - val_accuracy: 0.9231
Epoch 3/20
2/2 [==============================] - 0s 64ms/step - loss: 0.2282 - accuracy: 0.9412 - val_loss: 0.1929 - val_accuracy: 0.9231
Epoch 4/20
2/2 [==============================] - 0s 71ms/step - loss: 0.2277 - accuracy: 0.9412 - val_loss: 0.1947 - val_accuracy: 0.9231
Epoch 5/20
2/2 [==============================] - 0s 67ms/step - loss: 0.2273 - accuracy: 0.9412 - val_loss: 0.1956 - val_accuracy: 0.9231
Epoch 6/20
2/2 [==============================] - 0s 72ms/step - loss: 0.2269 - accuracy: 0.9412 - val_loss: 0.1973 - val_accuracy: 0.9231
Epoch 7/20
2/2 [==============================] - 0s 72ms/step - loss: 0.2263 - accuracy: 0.9412 - val_loss: 0.1986 - val_accuracy: 0.9231
Epoch 8/20
2/2 [==========

In [37]:
print("Test accuracy: ", accuracy_score(test_label, test_prediction_labels))
print("Test f1-score: ", f1_score(test_label, test_prediction_labels))
print("Test precision: ", precision_score(test_label, test_prediction_labels))
print("Test recall: ", recall_score(test_label, test_prediction_labels))

Test accuracy:  0.7700534759358288
Test f1-score:  0.8599348534201955
Test precision:  0.9777777777777777
Test recall:  0.7674418604651163


In [38]:
#Question 8
from keras.models import Sequential 
from keras. layers import Dense
from keras.optimizers import SGD
def build_model():
  model = Sequential() # create Sequential model
  model.add(Dense (100, activation = 'relu')) # input layer -› hidden layer 1
  model.add(Dense (100, activation = 'relu')) # input layer -> hidden layer 1
  model.add(Dense(1, activation = 'sigmoid')) # hidden layer 2 -> output layer
  return model

X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size=0.3, random_state=42)
learning_rate_options = [0.001, 0.01, 0.1]
# loop over learning rates
for learning_rate in learning_rate_options:
  model = build_model ()
  optimizer_to_run = SGD(lr=learning_rate)
  model.compile(loss = "binary_crossentropy", optimizer = optimizer_to_run, metrics = ['accuracy'])
  model.fit (X_train,y_train, validation_data=(X_val,y_val), epochs = 100, verbose=None)
  model.save("model_Ir"+str(learning_rate)+".h5")
  print("Learning rate:", learning_rate," Validation Accuracy:", model.evaluate(X_val, y_val, verbose=None))

/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Learning rate: 0.001  Validation Accuracy: [0.6845161318778992, 0.6666666865348816]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Learning rate: 0.01  Validation Accuracy: [0.608696699142456, 0.7083333134651184]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Learning rate: 0.1  Validation Accuracy: [0.7794175148010254, 0.7916666865348816]


In [46]:
from keras.models import Sequential 
from keras.layers import Dense
from keras.optimizers import SGD
def build_model(n_layers = 2):
  model = Sequential() # create Sequential model
  for i in range(n_layers):

    model.add(Dense(100, activation = 'relu')) # input layer -> hidden layer 1 model. add(Dense(1, activation = 'sigmoid')) # hidden layer 2 -› output layer
    return model


X_train, X_val, y_train, y_val = train_test_split(train_features, train_label, test_size=0.3, random_state=42)
layers = [1,2,3,4,5]
# loop over learning rates
for n_layer in layers:
   model = build_model(n_layer)
   optimizer_to_run = SGD (lr=0.1)
   model.compile(loss="binary_crossentropy", optimizer=optimizer_to_run, metrics=['accuracy'])
   model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=100, verbose=None)

   model.save("model_lr"+str(learning_rate)+". h5")
   print("Layers: ", n_layer," Validation Accuracy: ", model.evaluate(X_val,y_val, verbose=None))

/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  1  Validation Accuracy:  [1.5180182456970215, 0.0]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  2  Validation Accuracy:  [1.2829656600952148, 0.0]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  3  Validation Accuracy:  [1.386370062828064, 0.0]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  4  Validation Accuracy:  [1.344578742980957, 0.0]


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Layers:  5  Validation Accuracy:  [1.4963842630386353, 0.0]


In [47]:
# practice 9.1: setup iris dataset for multi-class classification
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()

# get features from iris data
X = iris["data"][:, :] # using all features

# get binary labels for binary classification
y = iris["target"]

print(X.shape)
print(y)

(150, 4)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [48]:
# practice 9.2: Define the neural network classifier with softmax function as output
from keras.models import Sequential
from keras.layers import Dense

model = Sequential() # initialize Sequential model
model.add(Dense(10, input_shape=(X.shape[1],), activation='relu')) # input layer -> hidden layer 1
model.add(Dense(5, activation='relu')) # hidden layer 1 -> hidden layer 2
model.add(Dense(3, activation='softmax')) # hidden layer 2 -> output layer (3 classes, use softmax function to calculate probability)

In [49]:
# Compile model, use categorical_crossentropy as loss function for softmax function
model.compile(loss='categorical_crossentropy',
optimizer='SGD',
metrics=['accuracy'])

In [50]:
# practice 9.3: Train the model on the training set
model.fit(X, y, validation_split = 0.2, epochs=10)

Epoch 1/10


ValueError: ignored

In [53]:
## re-fit model on the training features and one-hot encoding labels
import tensorflow as tf
y_onehot = tf.keras.utils.to_categorical(y, num_classes=3, dtype='float32')
print(y_onehot)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [56]:
model.fit(X, y_onehot, validation_split = 0.2, epochs=10)

Epoch 1/10


TypeError: ignored

In [57]:

learning_rate = 0.1
optimizer_to_run = SGD(lr=learning_rate)
model.compile(loss='binary_crossentropy', optimizer=optimizer_to_run, metrics=['accuracy'])


y_onehot = tf.keras.utils.to_categorical(y, num_classes=3, dtype='float32')
model.fit(X, y_onehot, validation_split=0.2, epochs=10)


Epoch 1/10


/usr/local/lib/python3.9/dist-packages/keras/optimizers/legacy/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


4/4 [==============================] - 1s 68ms/step - loss: 0.8863 - accuracy: 0.4083 - val_loss: 1.0395 - val_accuracy: 0.0000e+00
Epoch 2/10
4/4 [==============================] - 0s 14ms/step - loss: 0.7140 - accuracy: 0.4167 - val_loss: 0.8044 - val_accuracy: 0.0000e+00
Epoch 3/10
4/4 [==============================] - 0s 19ms/step - loss: 0.6917 - accuracy: 0.4250 - val_loss: 0.6873 - val_accuracy: 0.0000e+00
Epoch 4/10
4/4 [==============================] - 0s 15ms/step - loss: 0.6783 - accuracy: 0.4167 - val_loss: 0.6917 - val_accuracy: 0.0000e+00
Epoch 5/10
4/4 [==============================] - 0s 15ms/step - loss: 0.6739 - accuracy: 0.3750 - val_loss: 0.6963 - val_accuracy: 0.0000e+00
Epoch 6/10
4/4 [==============================] - 0s 20ms/step - loss: 0.6697 - accuracy: 0.4167 - val_loss: 0.7007 - val_accuracy: 0.0000e+00
Epoch 7/10
4/4 [==============================] - 0s 20ms/step - loss: 0.6659 - accuracy: 0.4167 - val_loss: 0.7050 - val_accuracy: 0.0000e+00
Epoch 8/10